language: go

go:
  - 1.9
  - master

install: true

sudo: false

matrix:
  allow_failures:
    - go: master
  fast_finish: true

notifications:
  email: false

before_install:
  - go get -t -v ....


before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v -r ./vendor/)
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get -u golang.org/x/lint/golint
  - go get github.com/nebulouslabs/go-upnp
  - go get github.com/tasushid/go-fastping
  - go get github.com/twitchtv/twirp
  - go get golang.org/x/crypto/sha3
  
script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go vet ./...
  - chmod +x ./test.sh && test.sh
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
