# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9 # Specify golang version

    working_directory: /go/src/github.com/space55/summertech-blockchain
    steps:
      - checkout

      - run: go test -v ./... # Run unit tests