// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accounts.proto

package accounts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GeneralRequest struct {
	AccountIndex         uint32   `protobuf:"varint,1,opt,name=accountIndex,proto3" json:"accountIndex,omitempty"`
	PrivateKey           string   `protobuf:"bytes,2,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralRequest) Reset()         { *m = GeneralRequest{} }
func (m *GeneralRequest) String() string { return proto.CompactTextString(m) }
func (*GeneralRequest) ProtoMessage()    {}
func (*GeneralRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{0}
}

func (m *GeneralRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralRequest.Unmarshal(m, b)
}
func (m *GeneralRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralRequest.Marshal(b, m, deterministic)
}
func (m *GeneralRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralRequest.Merge(m, src)
}
func (m *GeneralRequest) XXX_Size() int {
	return xxx_messageInfo_GeneralRequest.Size(m)
}
func (m *GeneralRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralRequest proto.InternalMessageInfo

func (m *GeneralRequest) GetAccountIndex() uint32 {
	if m != nil {
		return m.AccountIndex
	}
	return 0
}

func (m *GeneralRequest) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

type GeneralResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralResponse) Reset()         { *m = GeneralResponse{} }
func (m *GeneralResponse) String() string { return proto.CompactTextString(m) }
func (*GeneralResponse) ProtoMessage()    {}
func (*GeneralResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{1}
}

func (m *GeneralResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralResponse.Unmarshal(m, b)
}
func (m *GeneralResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralResponse.Marshal(b, m, deterministic)
}
func (m *GeneralResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralResponse.Merge(m, src)
}
func (m *GeneralResponse) XXX_Size() int {
	return xxx_messageInfo_GeneralResponse.Size(m)
}
func (m *GeneralResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralResponse proto.InternalMessageInfo

func (m *GeneralResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GeneralRequest)(nil), "accounts.GeneralRequest")
	proto.RegisterType((*GeneralResponse)(nil), "accounts.GeneralResponse")
}

func init() { proto.RegisterFile("accounts.proto", fileDescriptor_e1e7723af4c007b7) }

var fileDescriptor_e1e7723af4c007b7 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0xd2, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x06, 0x60, 0x57, 0xb1, 0xb6, 0x83, 0xae, 0x12, 0x2f, 0xd1, 0x83, 0x94, 0x9c, 0x0a, 0x42,
	0x0f, 0x7a, 0x57, 0x54, 0xb4, 0x94, 0xaa, 0x87, 0xd4, 0x17, 0x88, 0xe9, 0x6f, 0x29, 0xda, 0x64,
	0x4d, 0xd2, 0xea, 0xbe, 0x96, 0x4f, 0x28, 0xd6, 0xec, 0xe2, 0x82, 0xa7, 0xf4, 0xf8, 0xcf, 0x90,
	0x2f, 0xff, 0x61, 0x28, 0x57, 0x5a, 0xdb, 0x85, 0x09, 0xbe, 0x5f, 0x38, 0x1b, 0x2c, 0x6b, 0x57,
	0x59, 0x3c, 0x51, 0x3e, 0x80, 0x81, 0x53, 0x6f, 0x12, 0xef, 0x0b, 0xf8, 0xc0, 0x04, 0xed, 0xc6,
	0xed, 0xd0, 0x4c, 0xf0, 0xc9, 0xb3, 0x6e, 0xd6, 0xdb, 0x93, 0x8d, 0x19, 0x3b, 0x21, 0x2a, 0xdc,
	0x6c, 0xa9, 0x02, 0x46, 0x28, 0xf9, 0x66, 0x37, 0xeb, 0x75, 0xe4, 0x9f, 0x89, 0x38, 0xa5, 0xfd,
	0x5a, 0xf5, 0x85, 0x35, 0x1e, 0x8c, 0xd3, 0xce, 0x1c, 0xde, 0xab, 0x29, 0x56, 0x62, 0x47, 0x56,
	0xf1, 0xec, 0x6b, 0x8b, 0xda, 0x57, 0xb1, 0x0f, 0xbb, 0x21, 0x7a, 0xc4, 0x47, 0x8c, 0x8c, 0xf7,
	0xeb, 0xe2, 0xcd, 0x96, 0xc7, 0x47, 0xff, 0x6c, 0x7e, 0x7f, 0x12, 0x1b, 0x6c, 0x40, 0x79, 0x14,
	0xee, 0x9c, 0x9d, 0x8f, 0x50, 0xa6, 0x42, 0x43, 0x3a, 0x78, 0x50, 0xaf, 0xb8, 0x35, 0xda, 0x4e,
	0x66, 0x66, 0x3a, 0x56, 0x2f, 0x48, 0xa5, 0xee, 0xe9, 0x50, 0x42, 0xdb, 0x25, 0xdc, 0x8f, 0x52,
	0x89, 0xa9, 0xda, 0x25, 0xb5, 0xc6, 0xc1, 0xad, 0x01, 0x5c, 0xd0, 0xf6, 0x75, 0x19, 0xe0, 0x13,
	0xdf, 0x3f, 0xb7, 0x56, 0x87, 0x74, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xab, 0x1e, 0x1d, 0x2d,
	0x5a, 0x02, 0x00, 0x00,
}
